[package]
name = "ewe_svd"
version = "0.1.0"
edition = "2021"

[dependencies]
kzg = { version = "0.1.0", git = "https://github.com/grandinetech/rust-kzg.git" }
rust-kzg-blst = { version = "0.1.0", git = "https://github.com/grandinetech/rust-kzg.git" }
thiserror = "1.0.61"
blst = "0.3.12"
